name: pre-commit

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master

env:
  TERRAFORM_DOCS_VERSION: "v0.16.0"
  TFLINT_VERSION: "v0.40.1"
  CHECKOV_VERSION: "2.1.212"

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3

    - name: Install additional pre-commit hooks
      shell: bash
      run: |
        echo "########### Install Checkov ####################"
        pip install checkov==${{ env.CHECKOV_VERSION }}

        echo "########### Install Terraform-docs #############"
        wget https://github.com/terraform-docs/terraform-docs/releases/download/${{ env.TERRAFORM_DOCS_VERSION }}/terraform-docs-${{ env.TERRAFORM_DOCS_VERSION }}-linux-amd64.tar.gz
        tar xvzf terraform-docs-${{ env.TERRAFORM_DOCS_VERSION }}-linux-amd64.tar.gz
        mkdir -p ~/terraform-docs/bin/
        install terraform-docs ~/terraform-docs/bin/
        echo '~/terraform-docs/bin/' >> $GITHUB_PATH

        echo "########### Install Terraform-linters ##########"
        wget https://github.com/terraform-linters/tflint/releases/download/${{ env.TFLINT_VERSION }}/tflint_linux_amd64.zip
        unzip tflint_linux_amd64.zip
        mkdir -p ~/tflint/bin/
        echo '~/tflint/bin/' >> $GITHUB_PATH
        install tflint ~/tflint/bin/
        ~/tflint/bin/tflint --init

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0
